// Generated by CoffeeScript 1.3.3
(function() {
  var mustache, viewHelper, _;

  mustache = require('mustache');

  _ = require('underscore');

  viewHelper = {
    getView: function(build, view) {
      var currView;
      currView = require(build.appRoot + "/views/" + view + "/build.js");
      return currView.make(build);
    },
    setCSS: function() {},
    setJS: function() {},
    getIndex: function(build, content) {
      var baseIndexContent, baseIndexTemplate, indexTemplate;
      baseIndexTemplate = require(build.baseTemplate);
      indexTemplate = require(build.index);
      baseIndexContent = {
        template: mustache.render(indexTemplate, content)
      };
      return mustache.render(baseIndexTemplate, baseIndexContent);
    }
  };

  module.exports = viewHelper;

}).call(this);
