// Generated by CoffeeScript 1.3.3
(function() {
  var detect, uaParser;

  uaParser = require('ua-parser');

  detect = function(request) {
    var device, ua;
    ua = request.headers['user-agent'];
    device = {
      userAgent: ua,
      browser: uaParser.parse(ua),
      path: request.url,
      type: {}
    };
    if (/mobile/i.test(ua)) {
      device.type.mobile = true;
    }
    if (/Windows NT/.test(ua)) {
      device.type.windows = /Windows NT ([0-9\._]+)[\);]/.exec(ua)[1];
    }
    if (/(Intel|PPC) Mac OS X/.test(ua)) {
      device.type.mac = /(Intel|PPC) Mac OS X ?([0-9\._]*)[\)\;]/.exec(ua)[2].replace(/_/g, '.' || true);
    }
    if (/like Mac OS X/.test(ua)) {
      device.type.ios = /CPU( iPhone)? OS ([0-9\._]+) like Mac OS X/.exec(ua)[2].replace(/_/g, '.');
    }
    if (/like Mac OS X/.test(ua)) {
      device.type.iphone = /iPhone/.test(ua);
    }
    if (/like Mac OS X/.test(ua)) {
      device.type.ipad = /iPad/.test(ua);
    }
    if (/Android/.test(ua)) {
      device.type.android = /Android ([0-9\.]+)[\);]/.exec(ua)[1];
    }
    if (/webOS\//.test(ua)) {
      device.type.webos = /webOS\/([0-9\.]+)[\);]/.exec(ua)[1];
    }
    console.log(device);
    return device;
  };

  module.exports.detect = detect;

}).call(this);
