// Generated by CoffeeScript 1.3.3
(function() {
  var mustache, viewHelper, _;

  mustache = require('mustache');

  _ = require('underscore');

  viewHelper = {
    getView: function(build, view) {
      var currView;
      currView = require(build.appRoot + "/views/" + view + "/build.js");
      return currView.make(build);
    }
  };

  module.exports = viewHelper;

}).call(this);
