// Generated by CoffeeScript 1.3.3
(function() {
  var make, mustache, _;

  mustache = require('mustache');

  _ = require('underscore');

  make = function(build) {
    return '<h1>Here be Headers!</h1>';
  };

  module.exports.make = make;

}).call(this);
