// Generated by CoffeeScript 1.3.3
(function() {
  var app, builds, device, express, _;

  express = require('express');

  _ = require('underscore');

  builds = require('./lib/builds.js');

  device = require('./lib/helpers/device.js');

  app = express.createServer();

  app.configure(function() {
    return app.use('/', express["static"](__dirname + '/public'));
  });

  app.get('/', function(req, res) {
    var index;
    index = builds.route(device.detect(req));
    return res.send(index);
  });

  app.get('/view/*', function(req, res) {
    var index;
    index = builds.route(device.detect(req));
    return res.send(index);
  });

  app.get('/fetch/:format/', function(req, res) {
    var format;
    format = req.params['format'];
    return res.send(format);
  });

  app.listen(2323);

}).call(this);
