// Generated by CoffeeScript 1.3.3
(function() {
  var app, buildRouter, client, express, getApp;

  express = require('express');

  buildRouter = require('./lib/build_router.js');

  client = require('./lib/helpers/client.js');

  app = express.createServer();

  app.configure(function() {
    return app.use('/', express["static"](__dirname + '/public'));
  });

  getApp = function(req, res) {
    var index;
    index = buildRouter.getIndex(client.detect(req));
    return res.send(index);
  };

  app.get('/', function(req, res) {
    return getApp(req, res);
  });

  app.get('/view/*', function(req, res) {
    return getApp(req, res);
  });

  app.get('/fetch/:format/*', function(req, res) {
    var format;
    format = req.params['format'];
    return res.send(format);
  });

  app.listen(2323);

}).call(this);
