// Generated by CoffeeScript 1.3.3
(function() {
  var index;

  index = '\
<div id="header">{{{header}}}</div>\
<div id="mainWrap">\
	<div id="sidebar">{{{sidebar}}}</div>\
	<div id="content">{{{content}}}</div>\
</div>\
';

  module.exports = index;

}).call(this);
