// Generated by CoffeeScript 1.3.3
(function() {
  var BASE_TEMPLATE, config, getIndex, mustache, setCurrBuild, _;

  mustache = require('mustache');

  _ = require('underscore');

  config = require('./config.js');

  BASE_TEMPLATE = __dirname + '/indexes/base.js';

  setCurrBuild = function(client) {
    var build, builds, conf, currBuild, name;
    conf = config(client);
    builds = conf.defineBuilds();
    for (name in builds) {
      build = builds[name];
      if (build.condition) {
        build.name = name;
        build.client = client;
        build.baseTemplate = BASE_TEMPLATE;
        build.appRoot = __dirname;
        build.appDefaults = conf.appDefaults;
        delete build.condition;
        currBuild = build;
        break;
      }
    }
    return currBuild;
  };

  getIndex = function(client) {
    var builder, currBuild;
    currBuild = setCurrBuild(client);
    builder = require(currBuild.build);
    return builder.make(currBuild);
  };

  module.exports.getIndex = getIndex;

}).call(this);
