// Generated by CoffeeScript 1.3.3
(function() {
  var defineBuilds, mustache, route, router, _;

  mustache = require('mustache');

  _ = require('underscore');

  defineBuilds = function(device) {
    return {
      noJS: {
        build: '../lib/build/legacyBrowser.js',
        index: '../lib/indexes/legacyBrowser.js',
        condition: false
      },
      mobile: {
        build: '../lib/builds/mobile.js',
        init: '../lib/inits/mobile.js',
        index: '../lib/indexes/mobile.js',
        condition: false
      },
      tablet: {
        build: '../lib/builds/tablet.js',
        init: '../lib/inits/mobile.js',
        index: '../lib/indexes/tablet.js',
        condition: false
      },
      legacyBrowser: {
        build: '../lib/builds/legacyBrowser.js',
        init: '../lib/inits/legacyBrowser.js',
        index: '../lib/indexes/legacyBrowser.js',
        condition: false
      },
      modernBrowser: {
        build: '../lib/builds/modernBrowser.js',
        init: '../lib/inits/modernBrowser.js',
        index: '../lib/indexes/modernBrowser.js',
        condition: true
      }
    };
  };

  router = function(device) {
    var build, builds, currBuild, name;
    builds = defineBuilds(device);
    for (name in builds) {
      build = builds[name];
      if (build.condition) {
        build.name = name;
        currBuild = build;
        break;
      }
    }
    return currBuild;
  };

  route = function(device) {
    var build;
    route = router(device);
    build = require(route.build);
    return build.makeIndex(route);
  };

  module.exports.route = route;

}).call(this);
