// Generated by CoffeeScript 1.3.3
(function() {
  var config, _;

  _ = require('underscore');

  config = function(client) {
    return {
      client: client,
      appDefaults: {
        title: 'Welcome to our test site',
        metadata: {
          keywords: 'stuff otherstuff',
          description: 'this is a test site'
        }
      },
      defineBuilds: function() {
        var t;
        t = this;
        return {
          noJS: {
            build: __dirname + '/builders/legacyBrowser.js',
            index: __dirname + '/indexes/legacyBrowser.js',
            condition: false
          },
          mobile: {
            build: __dirname + '/builders/mobile.js',
            init: __dirname + '/inits/mobile.js',
            index: __dirname + '/indexes/mobile.js',
            condition: false
          },
          tablet: {
            build: __dirname + '/builders/tablet.js',
            init: __dirname + '/inits/mobile.js',
            index: __dirname + '/indexes/tablet.js',
            condition: false
          },
          legacyBrowser: {
            build: __dirname + '/builders/legacyBrowser.js',
            init: __dirname + '/inits/legacyBrowser.js',
            index: __dirname + '/indexes/legacyBrowser.js',
            condition: false
          },
          modernBrowser: {
            build: __dirname + '/builders/modernBrowser.js',
            init: __dirname + '/inits/modernBrowser.js',
            index: __dirname + '/indexes/modernBrowser.js',
            condition: true
          }
        };
      }
    };
  };

  module.exports = config;

}).call(this);
