// Generated by CoffeeScript 1.3.3
(function() {
  var builder, make, mustache, _;

  mustache = require('mustache');

  _ = require('underscore');

  builder = require('../../lib/helpers/builder.js');

  make = function(build) {
    var content, headerView;
    headerView = builder.getView(build, 'header');
    content = {
      header: headerView,
      sidebar: 'sidebar',
      content: '<pre>' + JSON.stringify(build, null, '    ') + '</pre>'
    };
    return builder.getIndex(build, content);
  };

  module.exports.make = make;

}).call(this);
