// Generated by CoffeeScript 1.3.3
(function() {
  var makeIndex, mustache, _;

  mustache = require('mustache');

  _ = require('underscore');

  makeIndex = function(route) {
    return 'here is the foo rendered index';
  };

  module.exports.makeIndex = makeIndex;

}).call(this);
